# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Spring-Petclinic Project Devops'
        organization: 'almos18'
        scannerMode: 'Other'
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

    - task: Docker@2
      inputs:
        containerRegistry: 'a'
        repository: 'abs1356 / spring-petclinic'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'

    - task: Docker@2
      inputs:
        containerRegistry: 'a'
        repository: 'abs1356 / spring-petclinic'
        command: 'push'
        tags: 'latest'